# Visualize the hidden layers of a classifier CNN

CAS AML Module3 by Beatriz Vidondo

Using keract: https://github.com/philipperemy/keract 

Keract toolkit allows to “get the activations (outputs) and gradients for each layer of Keras models” (Rémy, 2019)

Code adapted from https://www.machinecurve.com/index.php/2019/12/02/visualize-layer-outputs-of-your-keras-classifier-with-keract/

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
from tensorflow.keras import activations

# Model configuration
img_width, img_height = 28, 28
input_shape = (img_width, img_height, 1)
batch_size = 24
no_epochs = 100
no_classes = 3
validation_split = 0.1
verbosity = 1


In [2]:
data_dir_str = 'C:/Users/beatriz/Documents/Python/MyModule3/data/squarecircletriang/shapes/'

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir_str,
    #label_mode = None,
    validation_split=validation_split,
    subset="training",
    color_mode='grayscale',
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size)

test_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir_str,
    #label_mode = None,
    validation_split=validation_split,
    subset="validation",
    color_mode='grayscale',
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size)

# store and rescale the image data as well
input_train=np.concatenate(list(map(lambda x: x[0].numpy()/255, train_ds)))
input_test=np.concatenate(list(map(lambda x: x[0].numpy()/255, test_ds)))
print(input_train.shape)
print(input_test.shape)


Found 300 files belonging to 3 classes.
Using 270 files for training.
Found 300 files belonging to 3 classes.
Using 30 files for validation.
(270, 28, 28, 1)
(30, 28, 28, 1)


In [3]:
# store the labels sepparately
train_labels0=np.concatenate(list(map(lambda x: x[1].numpy(), train_ds))).astype(np.uint8)
test_labels0=np.concatenate(list(map(lambda x: x[1].numpy(), test_ds))).astype(np.uint8)
train_labels = train_labels0
test_labels = test_labels0
print(train_labels.shape)
print(test_labels.shape)

# Convert target vectors to categorical targets
target_train = tf.keras.utils.to_categorical(train_labels0, no_classes)
target_test = tf.keras.utils.to_categorical(test_labels0, no_classes)
print(target_train.shape)
print(target_test.shape)

(270,)
(30,)
(270, 3)
(30, 3)


In [8]:
# Create the model
model = Sequential()
model.add(Conv2D(16, kernel_size=(1, 1), activation='relu', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(10, kernel_size=(5, 5), activation='relu'))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(no_classes, activation='softmax'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 28, 28, 16)        32        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 10, 10, 10)        4010      
_________________________________________________________________
flatten_1 (Flatten)          (None, 1000)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               256256    
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 771       
Total params: 261,069
Trainable params: 261,069
Non-trainable params: 0
________________________________________________

In [6]:
# Compile the model
model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])

# Fit data to model
model.fit(input_train, target_train,
          batch_size=batch_size,
          epochs=no_epochs,
          verbose=verbosity,
          validation_split=validation_split)

# Generate generalization metrics
score = model.evaluate(input_test, target_test, verbose=0)
print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')

Epoch 1/100

11/11 [==============================] - 1s 34ms/step - loss: 1.1380 - accuracy: 0.3169 - val_loss: 1.1054 - val_accuracy: 0.2593
Epoch 2/100

11/11 [==============================] - 0s 17ms/step - loss: 1.1124 - accuracy: 0.3498 - val_loss: 1.1045 - val_accuracy: 0.2593
Epoch 3/100

11/11 [==============================] - 0s 18ms/step - loss: 1.0998 - accuracy: 0.3004 - val_loss: 1.0989 - val_accuracy: 0.3333
Epoch 4/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0986 - accuracy: 0.3580 - val_loss: 1.0998 - val_accuracy: 0.2593
Epoch 5/100

11/11 [==============================] - 0s 17ms/step - loss: 1.0984 - accuracy: 0.3498 - val_loss: 1.1007 - val_accuracy: 0.2593
Epoch 6/100

11/11 [==============================] - 0s 19ms/step - loss: 1.0985 - accuracy: 0.3498 - val_loss: 1.1026 - val_accuracy: 0.2593
Epoch 7/100

11/11 [==============================] - 0s 20ms/step - loss: 1.0983 - accuracy: 0.3498 - val_loss: 1.1039 - val_accuracy: 0.2593

Epoch 21/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1040 - val_accuracy: 0.2593
Epoch 22/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0982 - accuracy: 0.3498 - val_loss: 1.1040 - val_accuracy: 0.2593
Epoch 23/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0980 - accuracy: 0.3498 - val_loss: 1.1037 - val_accuracy: 0.2593
Epoch 24/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1038 - val_accuracy: 0.2593
Epoch 25/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1036 - val_accuracy: 0.2593
Epoch 26/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0982 - accuracy: 0.3498 - val_loss: 1.1056 - val_accuracy: 0.2593
Epoch 27/100

11/11 [==============================] - 0s 19ms/step - loss: 1.0983 - accuracy: 0.3498 - val_loss: 1.1065 - val_accuracy:

11/11 [==============================] - 0s 17ms/step - loss: 1.0982 - accuracy: 0.3498 - val_loss: 1.1048 - val_accuracy: 0.2593
Epoch 42/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0980 - accuracy: 0.3498 - val_loss: 1.1044 - val_accuracy: 0.2593
Epoch 43/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0980 - accuracy: 0.3498 - val_loss: 1.1047 - val_accuracy: 0.2593
Epoch 44/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0980 - accuracy: 0.3498 - val_loss: 1.1036 - val_accuracy: 0.2593
Epoch 45/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0984 - accuracy: 0.3498 - val_loss: 1.1028 - val_accuracy: 0.2593
Epoch 46/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0982 - accuracy: 0.3498 - val_loss: 1.1033 - val_accuracy: 0.2593
Epoch 47/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1028 - val_accuracy: 0.2593
Epoch 

11/11 [==============================] - 0s 16ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1030 - val_accuracy: 0.2593
Epoch 63/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1028 - val_accuracy: 0.2593
Epoch 64/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1029 - val_accuracy: 0.2593
Epoch 65/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1039 - val_accuracy: 0.2593
Epoch 66/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0980 - accuracy: 0.3498 - val_loss: 1.1042 - val_accuracy: 0.2593
Epoch 67/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1038 - val_accuracy: 0.2593
Epoch 68/100

11/11 [==============================] - 0s 16ms/step - loss: 1.0981 - accuracy: 0.3498 - val_loss: 1.1038 - val_accuracy: 0.2593
Epoch 

Epoch 83/100

11/11 [==============================] - 0s 17ms/step - loss: 1.0985 - accuracy: 0.3498 - val_loss: 1.1097 - val_accuracy: 0.2593
Epoch 84/100

11/11 [==============================] - 0s 19ms/step - loss: 1.0984 - accuracy: 0.3498 - val_loss: 1.1097 - val_accuracy: 0.2593
Epoch 85/100

11/11 [==============================] - 0s 19ms/step - loss: 1.0984 - accuracy: 0.3498 - val_loss: 1.1097 - val_accuracy: 0.2593
Epoch 86/100

11/11 [==============================] - 0s 20ms/step - loss: 1.0990 - accuracy: 0.3498 - val_loss: 1.1113 - val_accuracy: 0.2593
Epoch 87/100

11/11 [==============================] - 0s 21ms/step - loss: 1.0986 - accuracy: 0.3498 - val_loss: 1.1116 - val_accuracy: 0.2593
Epoch 88/100

11/11 [==============================] - 0s 17ms/step - loss: 1.0990 - accuracy: 0.3498 - val_loss: 1.1120 - val_accuracy: 0.2593
Epoch 89/100

11/11 [==============================] - 0s 15ms/step - loss: 1.0987 - accuracy: 0.3498 - val_loss: 1.1114 - val_accuracy:

In [10]:
# =============================================
# Keract visualizations
# =============================================
from keract import get_activations, display_activations
keract_inputs = input_test[:1]
keract_targets = target_test[:1]
activations = get_activations(model, keract_inputs)
display_activations(activations, cmap="gray", save=False)

conv2d_2_input (1, 28, 28, 1) 
conv2d_2 (1, 28, 28, 16) 
max_pooling2d_1 (1, 14, 14, 16) 
conv2d_3 (1, 10, 10, 10) 
flatten_1 (1, 1000) 
dense_2 (1, 256) 
dense_3 (1, 3) 


the Softmax layer generates three probabilities for the three classes: the last picture shows a white neuron (white equals ‘one’ or ‘true’), and two black neurons ('zero' or 'false'). 

The classes' order are circles, square and triangles

In [8]:
# =============================================
# Take a sample for visualization purposes
# =============================================
input_sample = input_test[:5]
predicted = model.predict([input_sample])

print(input_sample.shape)
print(predicted.shape)
print(predicted)

(5, 28, 28, 1)
(5, 3)
[[0.3264432  0.34173897 0.33181784]
 [0.3264432  0.34173897 0.33181784]
 [0.3264432  0.34173897 0.33181784]
 [0.3264432  0.34173897 0.33181784]
 [0.3264432  0.34173897 0.33181784]]
